### ISSUE TITLE
Ligatures LAM WITH ALEF with HAMZA/MADDA misposition diacritics

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1886]
Ligatures below misposition diacritics in NotoSansArabic/NotoSansArabicUI and NotoArabicNaskh/NotoArabicNaskhUI.

U+FEF5 ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM
U+FEF6 ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM

U+FEF7 ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM
U+FEF8 ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM
U+FEF9 ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM
U+FEFA ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM

In NotoSansArabic and NotoSansArabicUI: diacritics overlap HAMZA/MADDA in (U+FEF5, U+FEF6, U+FEF7, U+FEF8, U+FEF9, U+FEFA)
Note: There is another issue with positioning the MADDA filed in another bug https://github.com/googlefonts/noto-fonts/issues/1875 but this is different issue

In NotoArabicNaskh and NotoArabicNaskhUI: diacritics placed below the MADDA in (U+FEF5, U+FEF6) and below the HAMZA in (U+FEF7, U+FEF8), diacritics should placed above the HAMZA and the MADDA
Diacritics placed above the HAMZA in (U+FEF9, U+FEFA), diacritics should be placed below the HAMZA

<b>Issue found in:</b>
NotoSansArabic 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoSansArabicUI 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-Regular.ttf
NotoNaskhArabicUI Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
NotoNaskhArabicUI Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabicUI/NotoNaskhArabicUI-Regular.ttf
<b>Characters data used in the test below:</b>
ﻵً ﻶً ﻷً ﻸً ﻹٍ ﻺٍ

<img width="641" alt="Screen Shot 2020-10-08 at 10 10 14 AM" src="https://user-images.githubusercontent.com/22158882/95493759-c3fbeb80-0951-11eb-9b1a-b3c902b43d58.png">

**Comment by nizarsq** [comment]
Issues fixed in NotoSansArabic
<img width="1285" alt="Screen Shot 2020-11-11 at 5 25 12 PM" src="https://user-images.githubusercontent.com/22158882/98883169-dc748f80-2442-11eb-846a-c2cdb9b2bac5.png">

**Comment by nizarsq** [comment]
Issues fixed

**Comment by nizarsq** [comment]
This issue still need fix in NotoNaskhArabic/NotoNaskhArabicUI

**Comment by dscorbett** [comment]
The diacritics are still mispositioned in [Noto Naskh Arabic 2.006](https://github.com/googlefonts/noto-fonts/blob/e07e0aea978224aef9890a050809794ff6dfcc8f/unhinted/otf/NotoNaskhArabic/NotoNaskhArabic-Regular.otf).
![ﻵً ﻶً ﻷً ﻸً ﻹٍ ﻺٍ](https://user-images.githubusercontent.com/1124347/106003300-10de0c00-6080-11eb-83ea-28f64c63121c.png)

**Comment by dscorbett** [comment]
@nizarsq, please reopen this. Noto Naskh Arabic is still broken.

**Comment by nizarsq** [comment]
Thank you @dscorbett. @marekjez86 for evaluation.
Thanks

**Comment by dscorbett** [comment]
@marekjez86, please reopen this. Noto Naskh Arabic 2.012 is still broken.
