### ISSUE TITLE
NotoSerifTibetan-Regular.ttf: glyph དྡྷི is rendered incorrectly

### ISSUE THREAD

**Issue by domschl** [googlefonts/noto-fonts#2362]
Tibetan glyph དྡྷི (Wylie d+d+hi) is rendered as Wylie d+d+d+hi (three instead of two da)

Font source: https://fonts.google.com/noto/specimen/Noto+Serif+Tibetan (2022-05-20)
Font: NotoSerifTibetan-Regular, Version 2.001

Computer: macOS 12.4
Applications: all
<img width="248" alt="Screenshot 2022-05-20 at 19 17 18" src="https://user-images.githubusercontent.com/5649667/169580093-2ffcb217-9c5f-4d74-b645-4de60f7e08eb.png">

Red rectangle shows problem with NotoSerif.

**Comment by dscorbett** [comment]
This looks like #1528. The font has been fixed but the copy available on Google Fonts is out of date.

**Comment by domschl** [comment]
I've retested with latest version from <https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf>, and it is indeed fixed.

Glyph renders correctly with latest version.

Version number `2.001` of the font is however still the same as the release at Google Fonts.
